name: Frontend CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache NPM cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter (ESLint)
        run: npm run lint

      - name: Build frontend (Vite)
        run: npm run build

  auto-merge:
    needs: frontend-checks
    # Only on PRs targeting develop and not drafts
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      # change to squash/rebase if you prefer
      MERGE_METHOD: merge

    steps:
      # gh is preinstalled on ubuntu-latest; no checkout required
      - name: Set PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Enable auto-merge via gh
        env:
          GH_TOKEN: ${{ github.token }}   # <-- required for gh auth
        run: |
          case "$MERGE_METHOD" in
            merge|squash|rebase) ;;
            *) echo "Invalid MERGE_METHOD: $MERGE_METHOD"; exit 1 ;;
          esac
          gh pr merge -R "${{ github.repository }}" \
            --"$MERGE_METHOD" \
            --auto \
            "$PR_NUMBER"
